- name: mysql configuration
  hosts: mysql
  become: yes

  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start mysql server
    ansible.builtin.service:
      name: mysql-server
      state: started
      enabled: yes